export const MAP_TILE_SIZE = 16
export const MAP_TILE_SIZE_SCALE_FACTOR = 6;
export const MAP_TILE_SIZE_SCALED = MAP_TILE_SIZE * MAP_TILE_SIZE_SCALE_FACTOR
export const PLAYER_MIN_ATTACK_DISTANCE = MAP_TILE_SIZE_SCALED * 2;